config/routes.rb
Rails.application.routes.draw do
  root "posts#index"

  resources :posts
  resources :images, only: [:show, :new]
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post
  mount_uploader :file, AttachmentUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: :all_blank
  validates_presence_of :header, :reading_time, :excerpt, :body
  validates :reading_time, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @index = params[:index].to_i
    @post = Post.new
    @post.images.build
    render layout: false
  end

  def show
    image = Image.find(params[:id])
    send_file image.file.path, disposition: :inline
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
    @post.images.build
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      flash[:notice] = "Новая запись успешно опубликована."
      redirect_to @post
    else
      flash.now[:alert] = "Запись не была опубликована."
      render "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    @post.update(post_params)

    if @post.save
      flash[:notice] = "Запись была успешно изменена."
      redirect_to @post
    else
      flash.now[:alert] = "Запись не была изменена."
      render "edit"
    end
  end

  def destroy
    if @post.delete
      flash[:notice] = "Запись была успешно удалена."
      redirect_to posts_path
    end
  end


  private

  def set_post
    @post = Post.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "Такой записи тут нет."
    redirect_to posts_path
  end

  def post_params
    params.require(:post).permit(:header, :reading_time, :excerpt, :body,
    images_attributes: [:file, :file_cache])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(post_text)
    Markdown.new(post_text).to_html.html_safe
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/images/_form.html.erb
<%= f.simple_fields_for :images, child_index: index do |ff| %>
  <%= ff.input :file, as: :file, label: "Изображение №#{index += 1}" %>
  <%= ff.input :file_cache, as: :hidden %>
<% end %>

app/views/images/new.html.erb
<%= fields_for @post do |f| %>
  <%= render partial: "form", locals: { f: f, index: @index } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% flash.each do |key, message| %>
      <div class="">
        <%= message %>
      </div>
    <% end %>
    <div class="content column-12">
      <div class="header column-12">
        Логотип
        <div class="navigation">
          <%= link_to "Статьи", posts_path %>
        </div>
      </div>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for post do |f| %>
  <% if post.errors.any? %>
    <h2>Ошибки не позволяют опубликовать эту запись. Их количество - <%= post.errors.count %></h2>
    <ul>
      <% post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.input :header, label: "Тема" %>
  <%= f.input :reading_time, label: "Время чтения" %>
  <%= f.input :excerpt, label: "Краткое содержание" %>
  <%= f.input :body, label: "Текст" %>
  <div id="images">
    <h3>Изображения</h3>
    <%= render partial: "images/form", locals: { f: f, index: 0 } %>
  </div>
  <p>
    <%= link_to "Добавить ещё изображение", new_image_path, remote: true, id: "add_image",
                                            data: { params: { index: post.images.size } }%>
  </p>

  <%= f.submit "Опубликовать" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Редактировать</h1>
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<%= link_to "Новая запись", new_post_path, id: "new", class: "button" %>

<div class="posts column-12">
  <% @posts.each do |post| %>
    <div class="post_link column-12">
      <div class="column-9" id="posts_header"><%= link_to post.header, post, id: "post_link" %></div>
      <div class="column-9" id="posts_excerpt"><%= post.excerpt %></div>
      <div class="column-3" id="posts_reading_time">Время чтения: <%= post.reading_time %> мин.</div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Новая запись</h1>
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.header %></h1>
<div id="actions">
  <ul>
    <li><%= link_to "Редактировать", edit_post_path(@post), id: "edit", class: "button" %></li>
    <li><%= link_to "Удалить запись", post_path(@post), method: :delete,
                              data: { confirm: "Вы уверены, что хотите удалить эту запись?"}, id: "delete", class: "button" %></li>
  </ul>
</div>
<div class="column-3" id="reading_time">
  Время чтения <%= @post.reading_time %> мин.
</div>
<div class="content column-9" >
  <div id="excerpt">
    <%= @post.excerpt %>
  </div>
  <% if @post.images.any? %>
    <h4>Images</h4>
    <div class="images">
      <% @post.images.each do |image| %>
        <p>
          <%= link_to File.basename(image.file.url), image_path(image) %>
        </p>
      <% end %>
    </div>
  <% end %>
  <article class="post">
    <%= markdown(@post.body) %>
  </article>
</div>